
// const myheading= document.querySelector("h1");
// myheading.textContent="hello JS";
// console.log('hello world')

// ----------------------------------------------------------
// let icecream="chocolate";
// if( icecream==="chocolate"){
//     alert ("icecrem");
// }else{
//     alert("not ice");
// }

// --------------------------------------------------------------

// const heading=document.querySelector('h1');
// heading.addEventListener('click',updateName);
// function updateName(){
//     const name=prompt("enter new name");
//     heading.textContent=`player : ${name}`;
// }
let number = Math.floor((Math.random() * 100) + 1);
let chances = 0;
document.write("This is a guessing game and you have to enter a number and if it matches with the number generated by computer, then you win...\n");
let guess;
guess= prompt("Enter a number between 1 and 100");
chances++;
do{
  guess= Number.parseInt(guess);
  if (guess > number) {
    document.write("Number entered is greater");
    guess = prompt("Enter again!!");
    guess = Number.parseInt(guess);
    ++chances; 
    continue;
  }

  else if (guess < number) {
    document.write("Number entered is smaller");
    guess = prompt("Enter again!!");
    guess = Number.parseInt(guess);
    ++chances; 
  }

} while (guess != number); 

let score = 100 - chances;
document.write("\nCongratulations🥳🥳\nThe number generated was", number + " and you guessed it right😁\nYour final score is", score);

